#!/bin/bash
# Modified by Paskali
# Copyright (C) 2018 borgified <borgified@gmail.com>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${INTERFACE:-wlp2s0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

ESSID=$(iw dev $INTERFACE link | awk '/SSID:/{$1=""; print $0}')
ipv4=$(ip -4 addr show scope global | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)
ipv6=$(ip -6 addr show scope global | grep -oP '(?<=inet6\s)[\da-f:]+' | head -1)

#------------------------------------------------------------------------

if [ -n "$ipv4" ]; then
    echo $LABEL $ESSID \($ipv4\) # full text
elif [ -n "$ipv6" ]; then
    echo $LABEL $ESSID \($ipv6\)
else
    echo $LABEL $ESSID
fi

#echo $ESSID # short text
